CREATE TABLE data_meal_plan(
   meal_id              INTEGER  NOT NULL PRIMARY KEY 
  ,meal_type            VARCHAR(20) NOT NULL
  ,carb_name            VARCHAR(20) NOT NULL
  ,carb_energy_cal      INTEGER  NOT NULL
  ,carb_protein_g       NUMERIC(4,1) NOT NULL
  ,carb_fat_g           NUMERIC(4,1) NOT NULL
  ,carb_carb_g          NUMERIC(4,1) NOT NULL
  ,protein_name         VARCHAR(20) NOT NULL
  ,protein_energy_cal   INTEGER  NOT NULL
  ,protein_protein_g    NUMERIC(4,1) NOT NULL
  ,protein_fat_g        NUMERIC(4,1) NOT NULL
  ,protein_carb_g       NUMERIC(4,1) NOT NULL
  ,fruit_name           VARCHAR(20) NOT NULL
  ,fruit_energy_cal     INTEGER  NOT NULL
  ,fruit_protein_g      NUMERIC(3,1) NOT NULL
  ,fruit_fat_g          NUMERIC(3,1) NOT NULL
  ,fruit_carb_g         NUMERIC(4,1) NOT NULL
  ,vegetable_name       VARCHAR(20) NOT NULL
  ,vegetable_energy_cal INTEGER  NOT NULL
  ,vegetable_protein_g  NUMERIC(3,1) NOT NULL
  ,vegetable_fat_g      NUMERIC(4,1) NOT NULL
  ,vegetable_carb_g     NUMERIC(4,1) NOT NULL
);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (1,'normal','Bread',293,5.7,11,43.1,'Egg',127,12.6,8.5,0.3,'Grape',83,1.1,0.1,18.8,'Capsicum',20,1.5,0.1,2.3);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (3,'normal','Oats',389,8.3,7.5,69.1,'Milk',67,3.4,3.4,6,'Strawberry',26,0.7,0.2,3.9,'Asparagus',21,2.5,0.1,1.4);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (5,'normal','Rice',341,7.3,0.9,74,'Chicken',113,19.4,1.2,4.4,'Tangerine or tangor',43,1,0.2,8.1,'Bok choy',19,2.5,0.2,0.6);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (6,'normal','Couscous',364,13.8,0.2,73.6,'Beef',229,21.5,15.7,0.3,'Nectarine',43,1.2,0.1,8,'Tomato',16,0.5,0.1,2.2);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (7,'normal','Muesli',402,8.9,13.3,56.6,'Nut',570,19.7,50.5,5.4,'Banana',94,1.4,0.3,19.6,'Pumpkin',45,2.1,0.6,6.9);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (8,'normal','Rice',341,7.3,0.9,74,'Fish',178,18.4,11.7,0,'Apple',58,0.3,0.3,12,'Potato',226,3.8,10.1,28.2);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (9,'normal','Bread',293,5.7,11,43.1,'Cheese',375,20.3,32.4,0,'Kiwifruit',55,1.2,0.7,9.1,'Broccoli',31,4.7,0.3,0.4);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (10,'normal','Oats',389,8.3,7.5,69.1,'Yogurt',99,3.7,3.7,12.6,'Banana',94,1.4,0.3,19.6,'Sweet potato',70,1.9,0.1,14.1);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (13,'vegetarian','Oats',389,8.3,7.5,69.1,'Soy milk',67,3.4,3.4,6,'Strawberry',26,0.7,0.2,3.9,'Asparagus',21,2.5,0.1,1.4);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (17,'vegetarian','Muesli',402,8.9,13.3,56.6,'Nut',570,19.7,50.5,5.4,'Banana',94,1.4,0.3,19.6,'Pumpkin',45,2.1,0.6,6.9);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (18,'vegetarian','Rice',341,7.3,0.9,74,'Tofu',120,12,7.3,0,'Apple',58,0.3,0.3,12,'Mushroom',21,2.3,0.4,1.3);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (19,'vegetarian','Bread',293,5.7,11,43.1,'Cheese',375,20.3,32.4,0,'Kiwifruit',55,1.2,0.7,9.1,'Broccoli',31,4.7,0.3,0.4);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (20,'vegetarian','Oats',389,8.3,7.5,69.1,'Yogurt',99,3.7,3.7,12.6,'Banana',94,1.4,0.3,19.6,'Sweet potato',70,1.9,0.1,14.1);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (21,'vegan','Bread',293,5.7,11,43.1,'Baked beans',80,4.9,0.3,10.1,'Grape',83,1.1,0.1,18.8,'Capsicum',20,1.5,0.1,2.3);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (23,'vegan','Oats',389,8.3,7.5,69.1,'Tofu',120,12,7.3,0,'Strawberry',26,0.7,0.2,3.9,'Asparagus',21,2.5,0.1,1.4);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (25,'vegan','Rice',341,7.3,0.9,74,'Tofu',120,12,7.3,0,'Tangerine or tangor',43,1,0.2,8.1,'Bok choy',19,2.5,0.2,0.6);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (27,'vegan','Muesli',402,8.9,13.3,56.6,'Nut',570,19.7,50.5,5.4,'Banana',94,1.4,0.3,19.6,'Pumpkin',45,2.1,0.6,6.9);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (28,'vegan','Rice',341,7.3,0.9,74,'Nut',570,19.7,50.5,5.4,'Apple',58,0.3,0.3,12,'Capsicum',20,1.5,0.1,2.3);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (29,'vegan','Oats',389,8.3,7.5,69.1,'Soy milk',67,3.4,3.4,6,'Strawberry',26,0.7,0.2,3.9,'Asparagus',21,2.5,0.1,1.4);
INSERT INTO data_meal_plan(meal_id,meal_type,carb_name,carb_energy_cal,carb_protein_g,carb_fat_g,carb_carb_g,protein_name,protein_energy_cal,protein_protein_g,protein_fat_g,protein_carb_g,fruit_name,fruit_energy_cal,fruit_protein_g,fruit_fat_g,fruit_carb_g,vegetable_name,vegetable_energy_cal,vegetable_protein_g,vegetable_fat_g,vegetable_carb_g) VALUES (30,'vegan','Oats',389,8.3,7.5,69.1,'Almond Yogurt',99,3.7,3.7,12.6,'Banana',94,1.4,0.3,19.6,'Sweet potato',70,1.9,0.1,14.1);
